### ISSUE TITLE
using statements are not supported

### ISSUE THREAD

**Issue by sudface** [markw65/prettier-extension-monkeyc#13]
Hi!
Trying to optimise my program with the extension throws an error, because it doesn't appear to recognise the "using" keyword. I've attached a screenshot below.

In the prettier plugin, using statements do appear to be recognised [(v1.0.10)](https://github.com/markw65/prettier-plugin-monkeyc/blob/main/CHANGELOG.md#1010) but they don't seem to work with the optimiser extension. I suspect that the issue could also be because my `using` statement is inside the main class, not outside?

Cheers,
Sudarshan

![image](https://github.com/markw65/prettier-extension-monkeyc/assets/31204774/5393e22d-d580-4830-badd-cc900b73af8f)

**Comment by markw65** [comment]
> In the prettier plugin, using statements do appear to be recognised [(v1.0.10)](https://github.com/markw65/prettier-plugin-monkeyc/blob/main/CHANGELOG.md#1010)

That's a very old version of the plugin. But as far as I can tell it doesn't accept using/import inside a class either - I get errors when I try to format such code using prettier.

But the fix to the plugin was trivial. I've just published a fix (v1.0.52). Hopefully the fixing the extension will be similarly straightforward.

**Comment by markw65** [comment]
Fixed by f7a3d278ecd0f60ce7b0d993788425d298f87c21, and released as [v2.0.71](https://marketplace.visualstudio.com/items?itemName=markw65.prettier-extension-monkeyc)

**Comment by sudface** [comment]
Legend, all working now! The Monkey C language documentation really is a funny thing.
