### ISSUE TITLE
can't export project, alarm: ERROR: Internal: Error: ENOTEMPTY: directory not empty, rmdir

### ISSUE THREAD

**Issue by nnkn** [markw65/prettier-extension-monkeyc#16]
~~~bash
Starting optimization step...
ERROR: Internal: Error: ENOTEMPTY: directory not empty, rmdir 'd:\sync_DATA\GarminProjects\ManOfSteel\bin\optimized\group015-release\source\source-416'
Error: ENOTEMPTY: directory not empty, rmdir 'd:\sync_DATA\GarminProjects\ManOfSteel\bin\optimized\group015-release\source\source-416'
~~~
hi ,
it always alarm this, when I manually deleted the folder and try again , and it happs again.
I tried to export via `Monkey C: Export Project`, it works well.
I also tried to restart the computer, switch the computer(with the same project), it failed again and again.
what can I also do?
and what else I can offer to get rid of this?

thanks very much !

**Comment by markw65** [comment]
I've never seen anything like that... based on the name, I'm guessing that d:\sync_DATA is mapped to some kind of cloud storage? Microsoft OneDrive, or DropBox or iCloud, for example?

I'm hoping that's causing the problem, and if you can tell me exactly how things are setup, I might be able to repro and work around it...

**Comment by nnkn** [comment]
> I've never seen anything like that... based on the name, I'm guessing that d:\sync_DATA is mapped to some kind of cloud storage? Microsoft OneDrive, or DropBox or iCloud, for example?
> 
> I'm hoping that's causing the problem, and if you can tell me exactly how things are setup, I might be able to repro and work around it...

yes, I used syncthing to sync files between computers. I also tried  stopping the syncthing and then do the same job. still the same result.
I've tried to stop any programs I can stop. and it didn't work.
I tried to delete the files in bin/, sometimes I deleted success, sometimes success after I close the vscode. when I  do the job with empty bin/ , problem still....
I think there is something locked the file , but I can't figure out what it is.

**Comment by nnkn** [comment]
Maybe I should reinstall the Windows and do it again? but it's a great job....

**Comment by nnkn** [comment]
I don't know why, I just exit the huorong anti virus software (https://www.huorong.cn/), and then restart the vscode , I can successfully export the project....
I don't know why!
I don't know why!!
I don't know why!!!
because I have never! ever!! exited this software before , and export well, before yesterday~!!!!!!
![image](https://github.com/markw65/prettier-extension-monkeyc/assets/22342244/51e86377-17a3-47ca-95e2-b0738dc7ea6d)

sorry for interruption, maybe it did something I don't know ...
