### ISSUE TITLE
Unclear error message about missing compiled barrel

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/prettier-extension-monkeyc#18]
Sometimes it can be not easy to guess which project in the workspace misses compiled barrel file, as plugin reports error for not existing file:
```json
[{
	"resource": "/monkey.jungle",
	"owner": "analysis",
	"severity": 8,
	"message": "Failed to resolve some barrels: SomeBarrel",
	"source": "[pmc-analysis]",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```
There are no `monkey.jungle` file in the workspace root, as all projects are in their subdirectories. It would be nice, if error was pointing to specific project's `barrels.jungle`, where the missing barrel is referenced.

It can be reproduced in your [Barrels](https://github.com/markw65/Barrels) repo by removing `CompiledBarrel/bin/CompiledBarrel-0.0.0.barrel` file.

**Comment by markw65** [comment]
I think it's even easier. They should be included in the `buildDependencies`, and will automatically be watched by `addExtraFileWatchers`.

https://github.com/markw65/prettier-extension-monkeyc/blob/8850e8c00b14619454de48448d67b96e7b93b62a/src/project-manager.ts#L234

**Comment by markw65** [comment]
This was fixed a few releases ago, but I forgot to close it.
