### ISSUE TITLE
The terminal process terminated with exit code: 1.

### ISSUE THREAD

**Issue by La-S** [markw65/prettier-extension-monkeyc#2]
Hi markw65, first off, let me say that this extension is amazing, and is exactly what us MonkeyC developers need in order to have readable code and memory efficient code!! Thanks for putting this out there! 

I tried the latest version 2.0.0 on a very small app I have (uses 9.2 kb) and it instantly brought the app size down to 9.0kb.  Very cool!

I'm now trying to use it on a huge app I have (the code itself is 45kb of memory).  It also has multiple .mc files.  I'm getting this error: 

The terminal process "node '/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.0/bin/build.js', 'venu', '{"workspace":"/Users/myname/Documents/MyApp/MyApp","outputPath":"bin/optimized","jungleFiles":"monkey.jungle","developerKeyPath":"/Users/myname/Downloads/developer_key","typeCheckLevel":"Default","compilerWarnings":true,"name":"Run Optimized","request":"launch","type":"omonkeyc","device":"venu"}'" terminated with exit code: 1.

Is there something I can do to help identify where the error is getting snagged?

Thanks!

**Comment by markw65** [comment]
I think that if it was failing at build time you would get a meaningful error from the monkeyc compiler, so I think its not getting that far (you can probably check by seeing if it generated code under bin/optimized).

I've got a couple of small fixes that I was going to push today; but I'll add better diagnostics first so we can figure out what's going on.

**Comment by markw65** [comment]
I just pushed the new version. Hopefully, we get a better diagnostic message now.

**Comment by La-S** [comment]
Thank you for the update! The error codes are definitely more helpful!

I got this error with the new version: 

`ERROR: SyntaxError: source/MyApp.mc:171,7: Expected "(", ":", "[", "me", "self", "{", "}", comment, end of line, identifier, number, string, or whitespace but "-" found.`

Here's the code:

MyApp.mc:

170 var code_dict = {404=>"Your phone may not be connected to the internet.",  
171				  		-2=>"Bluetooth connection error.",
172				  		-104=>"Connect Phone"};

(I couldn't figure out how to get the code to format correctly using GitHub's code snippet feature.) In my code, I let each key have its own line for readability.

When I remove the negative keys for testing, the compiler gets farther, but then gets: 

`ERROR: Internal: TypeError: Cannot read properties of undefined (reading 'name')
The terminal process "node '/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.1/bin/build.js', 'venu', '{"workspace":"/Users/myname/Documents/MyApp/MyApp","outputPath":"bin/optimized","jungleFiles":"monkey.jungle","developerKeyPath":"/Users/myname/Downloads/developer_key","typeCheckLevel":"Default","compilerWarnings":true,"name":"Run Optimized","request":"launch","type":"omonkeyc","device":"venu"}'" terminated with exit code: 1.`


Thanks again for the latest update!

Lance

**Comment by markw65** [comment]
Thanks for the info. The first problem was just the parser being too restrictive, the new update should fix that. I can't tell what's going wrong for the Internal error,  but the new update will also dump a stack trace, which may pin it down. I should have done that last time.

Please update to latest and try again!

**Comment by La-S** [comment]
Thanks so much!  The parser works very nicely now!

Here's the error:

`ERROR: Internal: TypeError: Cannot read properties of undefined (reading 'push')
TypeError: Cannot read properties of undefined (reading 'push')
    at /Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:8374:53
    at Array.forEach (<anonymous>)
    at generateOptimizedProject (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:8367:11)
    at async buildOptimizedProject (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:8345:36)
The terminal process "node '/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/bin/build.js', 'venu', '{"workspace":"/Users/myname/Documents/MyApp/MyApp","outputPath":"bin/optimized","jungleFiles":"monkey.jungle","developerKeyPath":"/Users/myname/Downloads/developer_key","typeCheckLevel":"Default","compilerWarnings":true,"name":"Run Optimized","request":"launch","type":"omonkeyc","device":"venu"}'" terminated with exit code: 1.`

Again, thanks for all the time you've invested in this project!

**Comment by La-S** [comment]
Alright, I think we found the problem!

Using the excludeAnnotations gets us back to the original problem.

It appears the error is occurring because I have a 3rd party barrel in my app.  My code goes like this: 

`using KPayApp.KPay as KPay;`

The error I get from your code is this: 

`ERROR: Internal: TypeError: Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at /Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:7638:66
    at Array.forEach (<anonymous>)
    at processImports (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:7637:14)
    at analyze (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:7765:3)
    at async optimizeMonkeyC (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:7983:28)
    at async generateOneConfig (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:8480:20)
    at async Promise.all (index 0)
    at async generateOptimizedProject (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:8438:3)
    at async buildOptimizedProject (/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:8345:36)
The terminal process "node '/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/bin/build.js', 'venu', '{"workspace":"/Users/myname/Documents/MyApp/MyApp","outputPath":"bin/optimized","jungleFiles":"monkey.jungle","developerKeyPath":"/Users/myname/Downloads/developer_key","typeCheckLevel":"Default","compilerWarnings":true,"name":"Run Optimized","request":"launch","type":"omonkeyc","device":"venu"}'" terminated with exit code: 1.`

Adding some console.log statements to your code returns this object for KPay:

`{
  type: 'Using',
  id: {
    property: { type: 'Identifier', name: 'KPay', start: 62, end: 66 },
    computed: false,
    start: 54,
    end: 66,
    type: 'MemberExpression',
    object: { type: 'Identifier', name: 'KPayApp', start: 54, end: 61 }
  },
  as: { type: 'Identifier', name: 'KPay', start: 70, end: 74 },
  start: 48,
  end: 75
}`

I think we've almost got it!!

**Comment by markw65** [comment]
Yes, I've been adding a bunch of open source projects as tests, and I just found that one. I've also found several more, so I'm going to roll them all up into one update.
If you want to fix that one, locally, just change:

```
-    const [name, module] = lookup(node.id, node.as && node.as.id.name, stack);
+    const [name, module] = lookup(node.id, node.as && node.as.name, stack); 
```
in /Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.3/node_modules/@markw65/monkeyc-optimizer/build/optimizer.cjs:7638.

Meanwhile I will put a full fix later today, once I sort the other issues out.

That particular issue has nothing to do with barrels; I just had a bug with `using ... as` (none of my code uses the as clause, and nor do any of the Garmin sample apps). In fact, it looks like you could drop the as clause there, with no change to the meaning. But, I've not yet added barrel support; so I'm not sure what its going to do to your code...

**Comment by markw65** [comment]
New version is ready.

**Comment by La-S** [comment]
Thank you! We're so close! 

I can now remove the excludeAnnotations, and your code doesn't throw an error at that step!

Now I'm getting this error.

`ERROR: The Monkey Barrel dependency KPayApp (version 1.3.1) could not be resolved. Please make sure the barrel path was linked to within the main application's jungle file.
com.garmin.connectiq.common.manifest.ManifestException: [102] The Monkey Barrel dependency KPayApp (version 1.3.1) could not be resolved. Please make sure the barrel path was linked to within the main application's jungle file.
        at com.garmin.monkeybrains.ProjectBuilder.createBarrelContexts(ProjectBuilder.java:476)
        at com.garmin.monkeybrains.Monkeybrains.runPRGCompiler(Monkeybrains.java:1559)
        at com.garmin.monkeybrains.Monkeybrains.compileApplication(Monkeybrains.java:1335)
        at com.garmin.monkeybrains.Monkeybrains.run(Monkeybrains.java:2774)
        at com.garmin.monkeybrains.Monkeybrains.simpleMain(Monkeybrains.java:342)
        at com.garmin.monkeybrains.Monkeybrains.main(Monkeybrains.java:371)
usage: monkeyc [-a <arg>] [-b <arg>] [-c <arg>] [-d <arg>] [-e]
       [--Eno-invalid-symbol] [-f <arg>] [-g] [-h] [-i <arg>] [-k] [-l <arg>]
       [-m <arg>] [-o <arg>] [-p <arg>] [-r] [-s <arg>] [-t] [-u <arg>] [-v]
       [-w] [-x <arg>] [-y <arg>] [-z <arg>]
-a,--apidb <arg>       API import file
-b,--apimir <arg>      API MIR file
-c,--api-level <arg>   API Level to target
-d,--device <arg>      Target device
-e,--package-app       Create an application package.
   --Eno-invalid-symbolDo not error when a symbol is found to be invalid
-f,--jungles <arg>     Jungle files
-g,--debug             Print debug output
-h,--help              Prints help information
-i,--import-dbg <arg>  Import api.debug.xml
-k,--profile           Enable profiling support
-l,--typecheck <arg>   Type check [0=off, 1=gradual, 2=informative, 3=strict]
-m,--manifest <arg>    Manifest file (deprecated)
-o,--output <arg>      Output file to create
-p,--project-info <arg>projectInfo.xml file to use when compiling
-r,--release           Strip debug information
-s,--sdk-version <arg> SDK version to target (deprecated, use -c
-t,--unit-test         Enables compilation of unit tests
-u,--devices <arg>     devices.xml file to use when compiling (deprecated)
-v,--version           Prints the compiler version
-w,--warn              Show compiler warnings
-x,--excludes <arg>    Add annotations to the exclude list (deprecated)
-y,--private-key <arg> Private key to sign builds with
-z,--rez <arg>         Resource files (deprecated)
ERROR: Internal: 102
The terminal process "node '/Users/myname/.vscode/extensions/markw65.prettier-extension-monkeyc-2.0.4/bin/build.js', 'venu', '{"workspace":"/Users/myname/Documents/MyApp/MyApp","outputPath":"bin/optimized","jungleFiles":"monkey.jungle","developerKeyPath":"/Users/myname/Downloads/developer_key","typeCheckLevel":"Default","compilerWarnings":true,"name":"Run Optimized","request":"launch","type":"omonkeyc","device":"venu"}'" terminated with exit code: 1.`

I bet it has something to do with the barrel path.  In fact, I can copy the code from MyApp/bin/optimized/group000-debug/source, and put it in MyApp/source, and the compiler works correctly!

Thanks!

**Comment by markw65** [comment]
Right - all paths in jungle files are resolved relative to the jungle file itself. I'm generating the source paths, and updating the resource paths, but I'm not doing anything with the barrel paths, so since the jungle file is in another directory, it's not going to work. That should be easy enough to fix, but the real issue is what to do about the barrels themselves; the optimizer assumes its seen all of the code, and makes decisions accordingly. Code in barrels could break its assumptions.

Anyway, I've got a few more bugs to sort out that came up through testing more open source projects, and then I'll see what I can do about barrels.

**Comment by La-S** [comment]
Thank you! I'm guessing the barrel paths should appear in the debug.jungle file?

My monkey.jungle file is only one line: 

project.manifest = manifest.xml


The file .../group000-debug/source/debug.jungle doesn't say anything about barrels.

Here's a sample: 
project.manifest=../../manifest.xml
approachs60.sourcePath = group000-debug/**.mc
approachs60.resourcePath = ../../resources;../../resources-approachs60
approachs62.sourcePath = group000-debug/**.mc

Thanks!

**Comment by markw65** [comment]
I think the latest version should fix this. I still have some work to do to make it actually optimize barrel code. Please give it a try.

**Comment by La-S** [comment]
It works correctly now! It seems to take 1-1.5kb off my app size.  Very nice, thank you so much!

**Comment by markw65** [comment]
@La-S I just pushed v2.0.8 that adds full support for optimizing barrels.

If your barrels contain code, rather than just resources, this version should help more. I'd appreciate an update on whether it still works, and whether it gets better results. Thanks!

**Comment by La-S** [comment]
It works great. Now it knocks 1.6kb off! This optimizer is very helpful.  1.6 kb is a big deal when you're near the memory limit! Thank you!
