### ISSUE TITLE
Navigation to drawable in XML doesn't work

### ISSUE THREAD

**Issue by m4tiz5zktonj** [markw65/prettier-extension-monkeyc#20]
Earlier I used to click on id of drawable inside layout, and plugin opened their declarations, but this doesn't work in the current version.
```xml
<resources>
    <drawable-list id="Background">
        <shape type="rectangle" x="left" y="top" width="fill" height="fill" color="Graphics.COLOR_BLACK"/>
    </drawable-list>
    <layout id="Layout">
        <drawable id="Background"/>
    </layout>
</resources>
```

**Comment by markw65** [comment]
Can you identify a release where this worked?

**Comment by markw65** [comment]
No problem - this is obviously something that should be supported, but I couldn't see how it ever worked. I'll add it.
