### ISSUE TITLE
Export project seems to get hung up on Optimizing wf.original.iq to wf.iq step

### ISSUE THREAD

**Issue by jm355** [markw65/prettier-extension-monkeyc#24]
I've let it run overnight and still bin/exported/wf.iq shows as 0kb with no output on the terminal. Project I'm trying to export is here https://github.com/jm355/wf

**Comment by markw65** [comment]
Thanks for the test case - I'm looking at it now.

For what its worth, I find that for most projects, the source-to-source optimization step is around 10x faster than the garmin compile step, and then the post-build step is around the same speed as the source to source optimization. So once it's taken longer than garmin's compiler took, something has probably gone wrong...

**Comment by jm355** [comment]
After refreshing the folder, it looks like the post build finishes, the optimized .iq is smaller, but still the activity in vscode keeps spinning

**Comment by jm355** [comment]
Btw, if you have any tips for further optimizing my code I'd definitely appreciate it, but I recognize that's kind of a big ask so no worries if you don't want to :)

**Comment by markw65** [comment]
This seems to be a problem with the latest sdk - 7.4.3. They've changed the format of the manifest file slightly. The optimizer successfully optimizes all the .prg files in the .iq, but when it gets to the manifest, it throws an error - but I'm not handling it properly (I guess I've never had an error thrown at that point) - and it escapes without marking the build finished.

So yes, it's just sitting there spinning, after finishing everything except for updating the signatures in the manifest (so although it's more or less finished, the generated .iq file won't be accepted by the store).

If you go back to 7.3.1 it seems to work fine. I'll see what it takes to figure out the new format...

**Comment by markw65** [comment]
This is fixed in v2.0.116

> Btw, if you have any tips for further optimizing my code
I will take a look when I get some time
