### ISSUE TITLE
Empty function call is not reduced to empty

### ISSUE THREAD

**Issue by Ciantic** [markw65/prettier-extension-monkeyc#4]
I have this

```
import Toybox.System;
import Toybox.Lang;

(:inline,:debug)
function log(message as Lang.String) as Void {
    System.println(message);
}

(:inline,:release)
function log(message as Lang.String) {}
```

And when I optimize line like this:

```
log("Did something important");
```

It gives me in a release mode useless variable allocation:

```
{
    var message = "Did something important";
}
```

Naturally I don't want anything here.

Thanks, great tool!

**Comment by markw65** [comment]
What version are you using? With v2.0.25 I just get an empty pair of braces: `{ }`, and while thats not pretty, it doesn't actually generate any code.

On the other hand if I do something like `log("foo" + bar)`, I *do* get `{ var message = "foo" + bar; }`. That's something I'm working on fixing in a general way - ie cleaning things like that up independently of inlining, and I expect to release a fix in the next few days.

**Comment by markw65** [comment]
One other thing to note: Even once this is "fixed", things like `log(foo())` will still end up getting translated to something like `{ foo(); }` because the optimizer can't *not* call foo() just because its result isn't used.

One solution to this is something like:

```
(:debug)
const DEBUG = true;
(:release)
const DEBUG = false;
...
function whatever() {
  if (DEBUG) {
    log(foo());
  }
}
```

My optimizer will eliminate the `if` entirely in release builds (and also drop the test in debug builds, so there is no overhead to doing this).

**Comment by grigorye** [comment]
> My optimizer will eliminate the if entirely in release builds (and also drop the test in debug builds, so there is no overhead to doing this).

Just in case, if I get it correctly, this works with the default compiler nowadays as well.

**Comment by markw65** [comment]
> Just in case, if I get it correctly, this works with the default compiler nowadays as well

Yes. Garmin's optimizer does handle that particular example now. There are still similar cases it doesn't handle though.
